version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
    build:
        docker:
            - image: circleci/node:14.16.1
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            - workflows:
                heroku_deploy:
                  jobs:
                    - heroku/deploy-via-git